### ISSUE TITLE
The mp3importer.rb file is empty

### ISSUE THREAD

**Issue by iandevivi** [learn-co-students/ruby-collaborating-objects-lab-v-000#259]
I was looking for the solution to compare with my code and the mp3importer.rb file is empty and labeled as "new master".

**Comment by mjdele** [comment]
I was looking for the same and it is still empty.

**Comment by ga-be** [comment]
Hey guys- you can always try looking at the History of a file.

Hope this helps: https://github.com/learn-co-students/ruby-collaborating-objects-lab-v-000/blob/1ad6f0763743c7e3a21e7cd85e662b1a03e1d411/lib/mp3_importer.rb

**Comment by gj** [comment]
Also, [here](https://github.com/learn-co-curriculum/ruby-collaborating-objects-lab/blob/solution/lib/mp3_importer.rb)

**Comment by pletcher** [comment]
Fixed https://github.com/learn-co-students/ruby-collaborating-objects-lab-v-000/blob/solution/lib/mp3_importer.rb
