### ISSUE TITLE
Multiple spelling errors leading to failed tests

### ISSUE THREAD

**Issue by vicision** [learn-co-students/ruby-collaborating-objects-lab-v-000#300]
Specifically on the mp3_importer_spec.rb file, it says 'describe "Mp3Importer" do' when the tests are looking for "class MP3Importer"--the "P" should be capitalized as well. If a class Mp3Importer is built, the tests will fail. Also below this on the same spec file it says "describe 'intialize' do" rather than "describe 'initialize' do".

**Comment by gj** [comment]
@pletcher -- looks like [this change](https://github.com/learn-co-curriculum/ruby-collaborating-objects-lab/blob/0c49f7a6f61874a44d0dff506d235fefdf101120/spec/mp3_importer_spec.rb) didn't correctly propagate over here on the -students repo

**Comment by pletcher** [comment]
Pulled it in manually -- hopefully that'll resolve future syncing issues too
